# Generated by Django 5.2.9 on 2026-01-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_add',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_name_tr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_tr',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_tr',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
