# Generated by Django 5.2.9 on 2026-01-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0002_rename_created_add_booking_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='apartment_name_tr',
            new_name='apartment_name_ru',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='description_tr',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_name_tr',
            new_name='city_name_ru',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name_tr',
            new_name='country_name_ru',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_name_tr',
            new_name='service_name_ru',
        ),
    ]
