# Generated by Django 5.2.9 on 2026-01-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0003_rename_apartment_name_tr_apartment_apartment_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
