# Generated by Django 5.2.9 on 2026-01-20 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0004_userprofile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimages',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='airbnb_app.apartment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='airbnb_app.apartment'),
        ),
    ]
